apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ceph-exporter
  namespace: rook-ceph
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ceph-exporter
      name: ceph-exporter
    spec:
      containers:
      - name: ceph-exporter
        image: siangyeh8818/rook_ceph_exporter:1.0
        imagePullPolicy: Always
        commands:
        - "/bin/ceph_exporter"
        - "--ceph.config"
        - "/var/lib/rook/rook-ceph/rook-ceph.config"
        ports:
        - name: http-metrics
          containerPort: 9128
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /var/lib/rook/rook-ceph/
          name: ceph-cfg
          readOnly: true
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: ceph-cfg
        hostPath:
          path: /opt/rook/rook-ceph
