---
apiVersion: v1
kind: Service
metadata:
  name: ceph-exporter
  namespace: rook-ceph
  labels:
    k8s-app: ceph-exporter
spec:
  selector:
    app: ceph-exporter
  ports:
  - name: http-metrics
    port: 9128
    targetPort: 9128
